---
openai:
  enable: true
arithmetic:
  min: 2
  max: 10
  difficulty: 1
multiplication:
  count: 8
division:
  count: 8
area:
  count: 2
  difficulty: 1
cross_multiplication:
  count: 2
  openai_prompt: "schreibe eine dreisatz aufgabe mit text ohne lösung für die vierte klasse"
template: math_class_randomizer/templates/math_class.md.j2
markdown: math_class_randomizer/templates/math_class.md
